name: pre-commit checks

on: [push, pull_request]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@master
        with:
          python-version: 3.12

      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --show-diff-on-failure --from-ref origin/master --to-ref HEAD
